import tok


@tok.bridge
def process_payload(data):
    print(f"\n[Internal] Function received Tok:\n{data}")
    # Simulate a response that identifies what was received
    # The @tok.bridge decorator converts various formats into Tok BEFORE the function receives them.
    # We check for the specific Tok structures generated by each format.
    if "@data" in data:
        # JSON (Dict) -> @data
        return "@msg status:processed\n  |> JSON detected and processed."
    elif "@request" in data:
        # XML (String) -> @request (auto-detected based on <request> or similar)
        return "@msg status:processed\n  |> XML detected and processed."
    elif "@result" in data:
        # Markdown (Table) -> @result
        return "@msg status:processed\n  |> Markdown detected and processed."
    return "@msg status:unknown\n  |> Unknown format."


def main():
    print("--- MULTI-FORMAT BRIDGE DEMO ---")

    # 1. JSON (Dict)
    print("\n1. Testing JSON (Dict) -> Tok")
    res1 = process_payload({"id": 123, "type": "test"})
    print(f"Developer Received: {res1}")

    # 2. XML (String)
    print("\n2. Testing XML (String) -> Tok")
    xml_input = '<request id="456"><action>reboot</action></request>'
    res2 = process_payload(xml_input)
    print(f"Developer Received: {res2}")

    # 3. Markdown Table (String)
    print("\n3. Testing Markdown (Table) -> Tok")
    md_input = "| name | status |\n| --- | --- |\n| server1 | up |"
    res3 = process_payload(md_input)
    print(f"Developer Received: {res3}")

    # 4. Direct Call (Functional Style)
    print("\n4. Testing Direct Call (tok.bridge(content))")
    direct_tok = tok.bridge('{"direct": true}')
    print(f"Direct Tok output:\n{direct_tok}")


if __name__ == "__main__":
    main()
